sportapp/urls.py
from django.urls import path
import uuid
from sportapp import views

urlpatterns = [
    path('', views.Home1, name='Home1'),
    path('home/',views.Index,name='Home'),
    path('AddClub/', views.ClubsView, name='clubs'),
    path('superindent/<int:num>', views.superindent, name='superindent'),
    path('accept/<pk>', views.accept, name='accept'),
    path('deny/<pk>', views.deny, name='deny'),
    path('clubsList/',views.ClubsListView,name='clubsList'),
    path('editClub/<pk>/', views.UpdateClubsView, name='editClub'),
    path('<pk>/add_equipment/', views.EquipmentView, name='equipments'),
    path('<pk>/equipmentsList/', views.EquipmentListView, name='equipmentsList'),
    path('<pk>/<uuid:id>/delete/',views.deleteEquipmentView,name='equipmentDelete'),
    path('<pk>/<uuid:id>/Issue/',views.IssueFormView,name='Issue'),
    path('<pk>/IssueList/',views.IssueListView,name='IssueList'),
    path('total_list/',views.total_list,name='total_list'),
    path('Return/<int:pk>/<slug:id>',views.returnequipment,name='Return'),
    path('general/',views.general,name='general'),
    path('addgeneral/',views.addgeneral,name='addgeneral'),
    path('generalissue/<int:pk>',views.generalissue,name='generalissue'),
    path('generalIssueList/',views.generallist,name='generalIssueList'),
    path('generalreturn/<slug:id>',views.generalreturn,name='generalreturn'),
    path('generaldelete/<slug:id>',views.generaldelete,name='generaldelete'),
    path('gensecissuelist',views.gensecissuelist,name='gensecissuelist')

]

sportproject/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sportapp.urls')),
    path('oauth2/', include('django_auth_adfs.urls')),
    
]

sportapp/models.py
from django.db import models
from django.urls import reverse
# Create your models here.

from django.contrib.auth.models import User
import uuid


class clubs(models.Model):
    name = models.CharField(max_length=30,help_text='Enter a club name')
    secy_name= models.CharField(max_length=30,help_text='Enter a secy name')
    email=  models.EmailField()
    dept=models.CharField(max_length=40,help_text='Department')
    prog=models.CharField(max_length=50,help_text='Programme')
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('clubsList')    

class equipment(models.Model): 
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unique ID for this particular equipment')
    name = models.CharField(max_length=30)
    total_quantity= models.IntegerField(null=True)
    available_quantity=models.IntegerField(null=True)
    sport= models.ForeignKey('clubs', on_delete=models.CASCADE)
    specification=models.TextField(null=True)
    date=models.DateTimeField(auto_now=True)
    price=models.FloatField(null=True)
    def __str__(self):
        return self.name      

class issue(models.Model):
    equipment_name= models.ForeignKey('equipment',on_delete=models.CASCADE,null=True,default=None)
    general_equipname=models.ForeignKey('generalequipment',on_delete=models.CASCADE, null=True,default=None)
    roll= models.CharField(max_length=30) 
    name=  models.CharField(max_length=50)
    quantity= models.PositiveIntegerField(null=True)
    date= models.DateTimeField(auto_now=True)
    is_return= models.BooleanField(default=False)
    is_pending= models.BooleanField(default=True)
    req=models.BooleanField(default=False)
    remark=models.TextField(null=True,default=None)
    is_gen=models.BooleanField(default=False)
    user=models.ForeignKey('clubs',on_delete=models.CASCADE,null=True,default=None)  
    
    
   
    class Meta:
     ordering = ['date']
class generalequipment(models.Model):
    name = models.CharField(max_length=30)
    total_quantity= models.IntegerField(null=True)
    available_quantity=models.IntegerField(null=True)
    specification=models.TextField(null=True)
    price=models.FloatField(null=True)
    date=models.DateTimeField(auto_now=True)

    def __str__(self):
       return self.name    

sportapp/forms.py
from .models import *
from django import forms

departments=[('CSE','CSE'),('MNC','MNC'),('EEE','EEE'),('ECE','ECE'),('CL','CL'),('CST','CST'),('EP','EP'),('BT','BT'),('MECH','MECH'),('CIVIL','CIVIL'),('others','others')]
programs=[('BTECH','BTECH'),('MTECH','MTECH'),('B.DES','B.DES'),('M.DES','M.DES'),('PhD','PhD'),('M.S.(R)','M.S.(R)'),('M.A.','M.A.'),('M.Sc.','M.Sc.'),('others','others')]
class ClubForm(forms.ModelForm):
    dept=forms.CharField(widget=forms.Select(choices=departments))
    prog=forms.CharField(widget=forms.Select(choices=programs))
    class Meta:
        model=clubs
        fields = '__all__'
class EquipmentForm(forms.ModelForm):
    class Meta:
        model=equipment
        fields=['name','total_quantity','price','specification']

class IssueForm(forms.ModelForm):
    class Meta:
        model=issue
        fields=['roll','name','quantity']
class ReturnForm(forms.ModelForm):
    class Meta:
        model=issue
        fields=['roll','name','quantity']
class generalequipmentform(forms.ModelForm):
    class Meta:
        model=generalequipment
        fields=['name','total_quantity','price','specification']

class remarkform(forms.ModelForm):
    class Meta:
        model=issue
        fields=['remark']        

sportapp/views.py
from django.shortcuts import render
from django.views.generic.list import ListView
from django.views.generic.edit import UpdateView
from django.shortcuts import render, redirect,get_object_or_404
from django.contrib import messages
from .forms import *
from .models import *
from django.http import HttpResponse,Http404
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from datetime import datetime


def isgen(request):

    if request.user.email=="sportsec@iitg.ac.in":
        return True
    else :
        return False    


def issup(request):
    if request.user.email=="chrsports@iitg.ac.in":     # mail id of Superindent
        return True
    else :
        return False      

def allclubs() :
    clubs_list=clubs.objects.all()                                                         # all clublists
    return clubs_list
    
# Create your views here.
def Home1(request):
    return render(request,'sportapp/home1.html')

@login_required(redirect_field_name='')      
def Index(request):                                                                       # home page view
    clubs_list=clubs.objects.all()
    secy=0                                                                 # to separate general users from secy
    superin=issup(request)
    gensec=isgen(request)
    rem_clubs=[]
                                                                   # to separate general users from secy
   
    if(clubs.objects.filter(email=request.user.email)):                      #to find if user is secy of any club or general user
                clubs_list=clubs.objects.filter(email=request.user.email)
                rem_clubs=clubs.objects.exclude(email=request.user.email)      
                secy=1 
                


                
    elif(gensec or superin):
           secy=1
    
    
    context = {
            'clubs_list':clubs_list,
            'super':superin,
                 'gensec':gensec,
                 'isre':secy,
                  'rem':rem_clubs
                    }            
    return render(request,'sportapp/home.html',context)

    
@login_required(redirect_field_name='')    
def ClubsView(request):                                                                    # club adding view
  if isgen(request) or issup(request)  :                                                   # only visible to gensec and superindent
    if request.method == 'POST':
        
        form = ClubForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.save()
            return redirect('clubsList')

    else:
        form = ClubForm()
        context = {
            'form':form,
        }
    return render(request, 'sportapp/add_club.html', context)   
  raise Http404("Page does not exist")   


@login_required(redirect_field_name='')                     
def UpdateClubsView(request,pk):                                                             #pk of the club             # editing club information  
 if isgen(request) or issup(request) :                       
    if request.method == 'POST':
        form1 = ClubForm(request.POST)
        if form1.is_valid():
            form=form1.save(commit=False)
            clubs.objects.filter(pk=pk).update(name=form.name,secy_name=form.secy_name,email=form.email,dept=form.dept,prog=form.prog)
            return redirect('clubsList')

    else:
        club=clubs.objects.get(pk=pk)
        dict={                                              # for showing the prensent club information in the html form before editing (Get method)
            "name":club.name,
            "secy_name":club.secy_name,
            "email":club.email,
            "dept":club.dept,
            "prog":club.prog
        }
        form = ClubForm(initial=dict)
        context = {
            'form':form,
        }
    return render(request, 'sportapp/add_club.html', context)    

 raise Http404("Page does not exist")  
        

@login_required(redirect_field_name='')    
def ClubsListView(request): #   clubslist page view
 
  
  if isgen(request) or issup(request) :  
   
    gensec=0
    if isgen(request):
        gensec=1
    context={'clubs_list':allclubs(),'gensec':gensec,'super':issup(request)}
    return render(request,'sportapp/clubs_list.html',context)
  raise Http404("Page does not exist")
@login_required(redirect_field_name='')        
def EquipmentView(request,pk):                                                      # adding club equipments 
   if  issup(request):
    if request.method == 'POST':
        form = EquipmentForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.available_quantity=post.total_quantity        
            post.sport=clubs.objects.get(pk=pk)                                      # linking equipment to clubs table
            post.save()
            return redirect('equipmentsList',pk=pk)
    else:
            
        form = EquipmentForm()
        context = {
            'form':form,
        }
    return render(request, 'sportapp/add_equipment.html', context)    
   raise Http404("Page does not exist")   


@login_required(redirect_field_name='')          
def addgeneral(request):                                                                 #adding general equipments view
  if issup(request) :  
    if request.method == 'POST':
        form = generalequipmentform(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.available_quantity=post.total_quantity
            post.save()
            return redirect('general')
    else:       
        form = generalequipmentform()
        context = {
            'form':form,
        }
    return render(request, 'sportapp/add_equipment.html', context) 
  raise Http404("Page does not exist")      


def alphabet(d):                                                           #function for sorting based on name of the equipments
    return d.name        
@login_required(redirect_field_name='') 


def EquipmentListView(request,pk):                                        #Equipment list view

    clubs_list=clubs.objects.all()
    club=clubs.objects.get(pk=pk)                                           # retrieving the required club
    equipments=club.equipment_set.all()                                     # all equipments of the required club
    equipments1=list(equipments)                                            # converting the equipments in the required club to list data type to sort them in alphabetical order
    equipments1.sort(key=alphabet)            
    superin=issup(request)
    gensec=isgen(request)
    isre=0        
    rem_clubs=[]     
       
    ownclub=0                                                              # to separate general users from secy
   
    if(clubs.objects.filter(email=request.user.email)):                      #to find if user is secy of any club or general user
                clubs_list=clubs.objects.filter(email=request.user.email)
                rem_clubs=clubs.objects.exclude(email=request.user.email)      
                 
                isre=1   
                if(clubs.objects.get(email=request.user.email).email==club.email):
                   ownclub=1           
    elif(gensec or superin):
           isre=1

  
             
      
    context = {
             'clubs_list': clubs_list,
             'pk': pk,
            'equipments':equipments1,
            'super':superin,
            'gensec':gensec,
            'isre':isre,
            'rem':rem_clubs,
            
            'ownclub':ownclub
        }  
    
    return render(request, 'sportapp/equipments_list.html', context)   

@login_required(redirect_field_name='')    
def general(request):                #General equipment list view
 
    clubs_list=clubs.objects.all()
    equipments=generalequipment.objects.all()
    equipments1=list(equipments)       

    equipments1.sort(key=alphabet)
    superin=issup(request)
    gensec=isgen(request)
    isre=0
    rem_clubs=[]     
      
    if(clubs.objects.filter(email=request.user.email)):
                clubs_list=clubs.objects.filter(email=request.user.email)
                rem_clubs=clubs.objects.exclude(email=request.user.email)      
                 
                isre=1  
    elif(gensec or superin):
           isre=1  
        
    context = {
             'clubs_list': clubs_list,
            'equipments':equipments1,
            'super':superin,'gensec':gensec,
            'isre':isre,
            'rem':rem_clubs
         
        }  
  
    return render(request, 'sportapp/general.html', context)  


@login_required(redirect_field_name='')    
def deleteEquipmentView(request,id,pk):         #deleting equipments of club  
 if  issup(request)  : 
    if isgen(request) or issup(request) :
     a=equipment.objects.filter(id=id)              # id of the equipment
     a.delete()
     return redirect('equipmentsList',pk=pk)        # pk of the club
 else :
    raise Http404("Page does not exist")  


@login_required(redirect_field_name='')    
def generaldelete(request,id):                     # deleting general equipments
  if  issup(request):  
    a=generalequipment.objects.get(pk=id)
    a.delete()
    return redirect('general')                    # redirecting to general equipments list
  else :
    raise Http404("Page does not exist")


@login_required(redirect_field_name='')        
def IssueFormView(request,pk,id):                # issuing club equipments
   if  isgen(request) or clubs.objects.filter(email=request.user.email) : 
    equip=get_object_or_404(equipment, id=id)        # id of the equipment to te issued
   
    if request.method == 'POST':

        form = IssueForm(request.POST)
        if form.is_valid():
         post = form.save(commit=False)       

sportapp/templates/sportapp/Issue.html
<html>
    <head>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css">
        <style>
            /* Style the container */
            .container {
                    border-radius: 5px;
                    background-color: #f2f2f2;
                    padding: 20px 20px 70px 20px;
            }

            /* Style the submit button */
            input[type=submit] {
                    background-color: #009879;
                    color: white;
                    padding: 12px 20px;
                    border: none;
                    border-radius: 4px;
                    cursor: pointer;
                    float: left;
            }

            /* Style inputs, select elements and textareas */
            #quantity,select{
                    width: 100%;
                    padding: 8px;
                    border: 1px solid #ccc;
                    border-radius: 4px;
                    box-sizing: border-box;
                    resize: vertical;
            }

            /* Style the label to display next to the inputs */
            label {
                    padding: 12px 12px 12px 0;
                    display: inline-block;
            }
            h1{
                    font-family: "Trebuchet MS", sans-serif;
                    font-size: 2em;
                    letter-spacing: 0px;
                    border-bottom: 2px solid black;
                    text-transform: uppercase;
            }
        </style>
    </head>
    <body>
        <div class="container">
            <h1>issue here...</h1>
            {% load crispy_forms_tags %}
            <form method='post'>
                {% csrf_token %}
                <div>
                    {{form.roll | as_crispy_field }}
                </div>
                <div>
                    {{form.name | as_crispy_field}}
                </div>
                <div>
                    <label>Quantity</label>   
                    <input type="number" id="quantity" name="quantity" min="0" max="{{ maximum_value }}">
                <div>
                <br>
                <input type="submit" value = "submit">
            </form> 
        </div>
        
    </body>
</html>

sportapp/templates/sportapp/Issue_list.html
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" type="text/css" href="../../static/style.css">
<link rel="stylesheet" type="text/css" href="../../static/sidebar.css">

</head>




<body>

<div class="sidenav">
 {% if gensec or super %}
    <a href="{% url 'clubsList' %}">Secys</a>
    {% endif %}
    {%if super %}
    <a href="{% url 'superindent' 0 %}">Pending Requests</a>
    {% endif %}
    {% if clubs_list %}
    {% for club in clubs_list %}
  <button class="dropdown-btn">{{club.name}}
    <i class="fa fa-caret-down"></i>
  </button>
  <div class="dropdown-container">
    <a href="{% url 'equipmentsList' club.pk %}">Register stock</a>
    <a href="{% url 'IssueList' club.pk %}">Issue History</a>
  </div>
  {% endfor %}
  {% endif %}

     {% if rem %}
    {% for club in rem %}

  <button class="dropdown-btn">{{club.name}}
    <i class="fa fa-caret-down"></i>
    </button>


  </button>
  <div class="dropdown-container">
    <a href="{% url 'equipmentsList' club.pk %}">Register stock</a>
  </div>
  {% endfor %}
  {% endif %}

    <button class="dropdown-btn">General items
    <i class="fa fa-caret-down"></i>
  </button>
  <div class="dropdown-container">
     <a href="{% url 'general' %}">Register stock</a>
    <a href="{% url 'generalIssueList'   %}">Issue History</a>
  </div>
    {% if gensec %}
  <a href="{% url 'gensecissuelist' %}"> My_issues</a>
  {% endif %}
  {% if  super %}
    <a href="{% url 'total_list' %}"> Total Issues </a> 
    {% endif %}
  <a href="{% url 'django_auth_adfs:logout' %}">Logout</a>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>


<div class="main">

  <div class="header"><h1>Issue History</h1>
    <span>
    <select id="location-select" name="locationselect">
      <option value="">All</option>
      <option value="issued">Issued</option>
        <option value="issue denied">Issue denied</option>
      <option value="returned">Returned</option>
     
      <option value="return denied">Return denied</option>
      <option value="issue request pending">Issue request pending</option>
      <option value="return request pending">Return request pending</option>
    </select>
  
    <input type="text" id="myInput" onkeyup="myFunction()" placeholder="search here..." title="Type in a name">
    </span>
    <hr style="width:100%", size="3", color=black> 
  </div>
   
    {% if issue_list %}
    <table style="width:100%" class="styled-table" id="myTable" >
      <thead>
        <tr>
        <th> sno </th>
          <th>Id</th>
          {%if not super%}
          <th>student name</th>
          <th>roll number</th>
           {% endif %}
            <th>equipment Name</th>
            <th>specification</th>
            <th>Quantity</th>
            <th>Date of Issue/Return</th>
            <th>Issued To </th>
            <th>Remark</th>
            <th>status</th>

        </tr>
      </thead>
      <tbody>
      {% for obj in issue_list %}
      <tr>
      <td></td>
       <td>{{obj.pk}}</td>
        {% if not super%}
        <td>{{obj.name}}</td>
        <td>{{obj.roll}}</td>
         {% endif %}
        {%if obj.equipment_name %}
        <td>{{obj.equipment_name.name}}</td>
        <td>{{obj.equipment_name.specification}}</td>
        {%else %}
        <td>{{obj.general_equipname.name}}</td>
        <td>{{obj.general_equipname.specification}}
        {% endif %}

        <td>{{obj.quantity}}</td>
        <td>{{obj.date}}</td>
        {% if obj.is_gen%}
        <td>Gen secy</td>
        {%else%}
        <td>{{ obj.user.name }} Club secy</td>
        {% endif %}
        <td>{{obj.remark}}</td>
        {% if obj.is_return  %}
        {% if obj.is_pending %}
        <td class="pendingyellow">return request pending</td>
        {% else %}
        {% if obj.req%}
         <td class="acceptgreen">returned</td>
        {%else%}
           <td class="deniedred">return denied</td>
        {% endif %}
        {% endif %}
        {% else %}
        {% if obj.is_pending %}
        <td class="pendingyellow">issue request pending</td>
        {% else %}
        {%if obj.req%}
        <td class="acceptgreen">issued</td>
       {%else%}
       <td class="deniedred">issue denied</td>
       {%endif%}
        {% endif %}
        {% endif %}


      </tr>
    {% endfor %}
  </tbody>
</table>
  {% else %}
    <p>There are no Issue_Equipments </p>
  {% endif %}
</div>

 {% if not super %}
<script src="../../static/issue_list_search.js">
  </script>
{% else %}
<script src="../../static/issue_list_superindent_search.js" > 
</script> 
{% endif %}

<script src="../../static/sidebar.js">
</script>

</body>
</html>

sportapp/templates/sportapp/Total_list.html
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" type="text/css" href="../../static/style.css">
<link rel="stylesheet" type="text/css" href="../../static/sidebar.css">

</head>




<body>

<div class="sidenav">
 {% if gensec or super %}
    <a href="{% url 'clubsList' %}">Secys</a>
    {% endif %}
    {%if super %}
    <a href="{% url 'superindent' 0 %}">Pending Requests</a>
    {% endif %}
    {% if clubs_list %}
    {% for club in clubs_list %}
  <button class="dropdown-btn">{{club.name}}
    <i class="fa fa-caret-down"></i>
  </button>
  <div class="dropdown-container">
    <a href="{% url 'equipmentsList' club.pk %}">Register stock</a>
    <a href="{% url 'IssueList' club.pk %}">Issue History</a>
  </div>
  {% endfor %}
  {% endif %}
    <button class="dropdown-btn">General items
    <i class="fa fa-caret-down"></i>
  </button>
  <div class="dropdown-container">
     <a href="{% url 'general' %}">Register stock</a>
    <a href="{% url 'generalIssueList'   %}">Issue History</a>
  </div>
    {% if gensec %}
  <a href="{% url 'gensecissuelist' %}"> My_issues</a>
  {% endif %}
  {% if super  %}
    <a href="{% url 'total_list' %}"> Total Issues </a> 
    {% endif %}
  <a href="{% url 'django_auth_adfs:logout' %}">Logout</a>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>


<div class="main">

  <div class="header"><h1>Issue History</h1>
    <span>
    <select id="location-select" name="locationselect">
      <option value="">All</option>
      <option value="issued">Issued</option>
        <option value="issue denied">Issue denied</option>
      <option value="returned">Returned</option>
     
      <option value="return denied">Return denied</option>
      <option value="issue request pending">Issue request pending</option>
      <option value="return request pending">Return request pending</option>
    </select>
  
    <input type="text" id="myInput" onkeyup="myFunction()" placeholder="search here..." title="Type in a name">
    </span>
    <hr style="width:100%", size="3", color=black> 
  </div>

  
    {% if issue_list %}
    <table style="width:100%" class="styled-table" id="myTable" >
      <thead>
        <tr>
          <th>sno</th>
          <th>Id</th>
          {%if not super%}
          <th>student name</th>
          <th>roll number</th>
           {% endif %}
            <th>equipment Name</th>
            <th>specification</th>
            <th>Quantity</th>
            <th>Date of Issue/Return</th>
            <th>Issued To </th>
            <th>Remark</th>
            <th>status</th>

        </tr>
      </thead>
      <tbody>
      {% for obj in issue_list %}
      <tr>
       <td></td>
       <td>{{obj.pk}}</td>
        {% if not super%}
        <td>{{obj.name}}</td>
        <td>{{obj.roll}}</td>
         {% endif %}
        {%if obj.equipment_name %}
        <td>{{obj.equipment_name.name}}</td>
        <td>{{obj.equipment_name.specification}}</td>
        {%else %}
        <td>{{obj.general_equipname.name}}</td>
        <td>{{obj.general_equipname.specification}}
        {% endif %}

        <td>{{obj.quantity}}</td>
        <td>{{obj.date}}</td>
        {% if obj.is_gen%}
        <td>Gen secy</td>
        {%else%}
        <td>{{ obj.user.name }} Club secy</td>
        {% endif %}
        <td>{{obj.remark}}</td>
        {% if obj.is_return  %}
        {% if obj.is_pending %}
         <td class="pendingyellow">return request pending</td>
        {% else %}
        {% if obj.req%}
           <td class="acceptgreen">returned</td>
        {%else%}
       <td class="deniedred">return denied</td>
        {% endif %}
        {% endif %}
        {% else %}
        {% if obj.is_pending %}
        <td class="pendingyellow">issue request pending</td>
        {% else %}
        {%if obj.req%}
        <td class="acceptgreen">issued</td>
       {%else%}
      <td class="deniedred">issue denied</td>
       {%endif%}
        {% endif %}
        {% endif %}


      </tr>
    {% endfor %}
  </tbody>
</table>
  {% else %}
    <p>There are no Issue_Equipments </p>
  {% endif %}
</div>


 {% if not super %}
<script src="../../static/issue_list_search.js">
  </script>
{% else %}
<script src="../../static/issue_list_superindent_search.js">
 </script>
{% endif %}

<script src="../../static/sidebar.js">
</script>

</body>
</html>

sportapp/templates/sportapp/add_club.html
<html>
    <head>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css">
        <style>
            /* Style the container */
            .container {
                    border-radius: 5px;
                    background-color: #f2f2f2;
                    padding: 20px 20px 70px 20px;
            }

            /* Style the submit button */
            input[type=submit] {
                    background-color: #009879;
                    color: white;
                    padding: 12px 20px;
                    border: none; 
                    border-radius: 4px;
                    cursor: pointer;
                    float: left;
            }
            h1{
                    font-family: "Trebuchet MS", sans-serif;
                    font-size: 2em;
                    letter-spacing: 0px;
                    border-bottom: 2px solid black;
                    text-transform: uppercase;
            }

        </style>
    </head>
    <body>
        <div class="container">
            <h1>Add Your Club Here...</h1>
            {% load crispy_forms_tags %}
            <form method='post'>
                {% csrf_token %}
                {{ form|crispy }}
                <input type="submit" value = "submit">
            </form> 
        </div>
        
    </body>
</html>

sportapp/templates/sportapp/add_equipment.html
<html>
    <head>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css">
        <style>
            /* Style the container */
            .container {
                    border-radius: 5px;
                    background-color: #f2f2f2;
                    padding: 20px 20px 70px 20px;
            }

            /* Style the submit button */
            input[type=submit] {
                    background-color: #009879;
                    color: white;
                    padding: 12px 20px;
                    border: none;
                    border-radius: 4px;
                    cursor: pointer;
                    float: left;
            }
            h1{
                    font-family: "Trebuchet MS", sans-serif;
                    font-size: 2em;
                    letter-spacing: 0px;
                    border-bottom: 2px solid black;
                    text-transform: uppercase;
            }

        </style>
    </head>
    <body>
        <div class="container">
            <h1>Add your equipments here...</h1>
            {% load crispy_forms_tags %}
            <form method='post'>
                {% csrf_token %}
                {{ form|crispy }}
                <input type="submit" value = "submit">
            </form> 
        </div>
        
    </body>
</html>